/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View, Image } from 'react-native';
import ImageProcessingTools from 'react-native-image-processing-tools';

const imageUrl = 'https://images.unsplash.com/photo-1536602295863-59cf052c35f5?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=2636&q=80';

export default class App extends Component {

  constructor() {
    super();
    
    this.state = {
      status: 'starting',
      processedImage: ''
    };

    this.getImageProcessed = this.getImageProcessed.bind(this);
  }

  

  componentDidMount() {
    ImageProcessingTools.getBlackAndWhiteImageFromUrl(imageUrl, (response) => {
      this.setState({processedImage:response});
    });
  }

  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>Original Image</Text>
        <Image source={{uri:imageUrl}} style={{width:320, height:191}} />
        <Text style={styles.welcome}>Processed Image</Text>
        {this.getImageProcessed()}
      </View>
    );
  }

  getImageProcessed() {
    if (this.state.processedImage.length > 0) {
      return <Image source={{uri:this.state.processedImage}} style={{width:320, height:191}} />
    } else {
      return <View style={{width:320, height:191, justifyContent:'center', alignItems:'center', backgroundColor:'grey'}}>
        <Text>No image to display</Text>
      </View>
    }
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
